name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://idoshirhen.github.io/BarMitzvah/

      - name: Commit sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "Generate sitemap" || echo "No changes"
          git push
